<?php

// prevent this file from being accessed directly
if (!defined('WB_PATH'))
    die(header('Location: index.php'));

global $database;

/**
 *
 *
 * Update from Version 1.20 to newer Versions
 *
 *
 */

/*
 * create the new settings-table
 */
// Check if the table has still it's old format
// (Maybe this script runs a second time, so wo don't have to run the whole scruipt again
$oldFormat = true;
$sql = "SHOW FIELDS FROM `" . TABLE_PREFIX . "mod_foldergallery_settings`";
$query = $database->query($sql);
while ($row = $query->fetchRow()) {
    if ($row['Field'] == 's_name') {
        $oldFormat = false;
        break;
    }
}

if ($oldFormat) {
    // Save the old Settings
    $sql = "SELECT * FROM `" . TABLE_PREFIX . "mod_foldergallery_settings`";
    $query = $database->query($sql);
    while ($row = $query->fetchRow()) {
        $settings[] = $row;
    }

    // Delete the old Settings Table
    $database->query("DROP TABLE IF EXISTS `" . TABLE_PREFIX . "mod_foldergallery_settings`;");

    // Create the new Settings Table
    $sql = "CREATE TABLE IF NOT EXISTS `" . TABLE_PREFIX . "mod_foldergallery_settings` ("
            . "`id` int(11) NOT NULL AUTO_INCREMENT,"
            . "`section_id` int(11) NOT NULL,"
            . "`s_name` varchar(100) NOT NULL,"
            . "`s_value` TEXT NOT NULL,"
            . "PRIMARY KEY (`id`));";
    $database->query($sql);

    // Write the new Settings
    foreach ($settings as $value) {
        $section_id = $value['section_id'];
        foreach ($value as $key => $val) {
            // Prevent entries with numeric values (they are generated by fetchRow)
            if (is_numeric($key)) {
                continue;
            }
            // The following values are no longer needed
            if ($key == 'section_id') {
                continue;
            }
            if ($key == 'thumb_size') {
                continue;
            }
            if ($key == 'ratio') {
                continue;
            }

            $sql = "INSERT INTO `" . TABLE_PREFIX . "mod_foldergallery_settings` (`id`, `section_id`, `s_name`, `s_value`) VALUES "
                    . "(null, '" . $section_id . "', '" . $key . "', '" . $val . "');";
            $database->query($sql);
        }
        // OK, Update ThumbSettings:
        switch ($value['ratio']) {
            case 1:
                $thumbSettings = array(
                    'image_resize'  => true,
                    'image_x'       => $value['thumb_size'],
                    'image_y'       => $value['thumb_size']
                );
                break;
            case 1.3333:
                $thumbSettings = array(
                    'image_resize'  => true,
                    'image_x'       => $value['thumb_size'],
                    'image_y'       => floor($value['thumb_size']*3/4)
                );
                break;
            case 0.75:
                $thumbSettings = array(
                    'image_resize'  => true,
                    'image_x'       => floor($value['thumb_size']*3/4),
                    'image_y'       => $value['thumb_size']
                );
                break;
            case 1.7778:
                $thumbSettings = array(
                    'image_resize'  => true,
                    'image_x'       => $value['thumb_size'],
                    'image_y'       => floor($value['thumb_size']*9/16)
                );
                break;
            case 0.5625:
                $thumbSettings = array(
                    'image_resize'  => true,
                    'image_x'       => floor($value['thumb_size']*9/16),
                    'image_y'       => $value['thumb_size']
                );
            default:
                break;
        }
        // Set the default values
        $thumbSettings['image_ratio_fill'] = false;
        $thumbSettings['image_ratio_crop'] = true;
        $thumbSettings['image_background_color'] = '#FFFFFF';
        

        $sql = "INSERT INTO `" . TABLE_PREFIX . "mod_foldergallery_settings` (`id`, `section_id`, `s_name`, `s_value`) VALUES "
             . "(null, '" . $section_id . "', 'tbSettings', '".serialize($thumbSettings)."');";
        $database->query($sql);
    }
}
/**
 * END create the new settings table
 */


/**
 * alter categories Table to allow more than 255 characters as categoriedescription
 */
$sql = "ALTER TABLE `".TABLE_PREFIX."mod_foldergallery_categories` CHANGE `description` `description` TEXT NOT NULL DEFAULT '';";
$database->query($sql);
/**
 * END alter categories Table
 */

?>
