<?php

// prevent this file from being accessed directly
if (!defined('WB_PATH'))
    die(header('Location: index.php'));

global $database;

/**
 *
 *
 * Update from Version 1.20 to newer Versions
 *
 *
 */

/*
 * create the new settings-table
 */
// Check if the table has still it's old format
// (Maybe this script runs a second time, so wo don't have to run the whole scruipt again
$oldFormat = true;
$sql = "SHOW FIELDS FROM `" . TABLE_PREFIX . "mod_foldergallery_settings`";
$query = $database->query($sql);
while ($row = $query->fetchRow()) {
    if ($row['Field'] == 's_name') {
        $oldFormat = false;
        break;
    }
}

if ($oldFormat) {
    // Save the old Settings
    $sql = "SELECT * FROM `" . TABLE_PREFIX . "mod_foldergallery_settings`";
    $query = $database->query($sql);
    while ($row = $query->fetchRow()) {
        $settings[] = $row;
    }

    // Delete the old Settings Table
    $database->query("DROP TABLE IF EXISTS `" . TABLE_PREFIX . "mod_foldergallery_settings`;");

    // Create the new Settings Table
    $sql = "CREATE TABLE IF NOT EXISTS `" . TABLE_PREFIX . "mod_foldergallery_settings` ("
            . "`id` int(11) NOT NULL AUTO_INCREMENT,"
            . "`section_id` int(11) NOT NULL,"
            . "`s_name` varchar(100) NOT NULL,"
            . "`s_value` TEXT NOT NULL,"
            . "PRIMARY KEY (`id`));";
    $database->query($sql);

    foreach ($settings as $value) {
        $section_id = $value['section_id'];
        foreach ($value as $key => $val) {
            // Prevent entries with numeric values (they are generated by fetchRow)
            if (is_numeric($key)) {
                continue;
            }
            // The section_id is no longer neded as there is a special colum for this
            if ($key == 'section_id') {
                continue;
            }
            $sql = "INSERT INTO `" . TABLE_PREFIX . "mod_foldergallery_settings` (`id`, `section_id`, `s_name`, `s_value`) VALUES "
                    . "(null, '" . $section_id . "', '" . $key . "', '" . $val . "');";
            $database->query($sql);
        }
    }
}
/**
 * END create the new settings table
 */


?>
