<?php

// prevent this file from being accessed directly
if (!defined('WB_PATH'))
    die(header('Location: index.php'));

global $database;

/*******************************************************************************
 *
 * Update from Version 1.20/1.21 to newer Versions
 *
 * * new Settings Table
 * * new Thumbnail-Settings
 * * categorie text field now as text
 * * delete unused files (many of them are moved to the admin folder)
 *
 ******************************************************************************/

/*
 * BEGIN: Create new settings table
 */

// Check if the table has still it's old format
// (Maybe this script runs a second time, so wo don't have to run the whole script again
$oldFormat = true;
$sql = "SHOW FIELDS FROM `" . TABLE_PREFIX . "mod_foldergallery_settings`";
$query = $database->query($sql);
while ($row = $query->fetchRow()) {
    if ($row['Field'] == 's_name') {
        $oldFormat = false;
        break;
    }
}

if ($oldFormat) {
    // Save the old Settings
    $sql = "SELECT * FROM `" . TABLE_PREFIX . "mod_foldergallery_settings`";
    $query = $database->query($sql);
    while ($row = $query->fetchRow()) {
        $settings[] = $row;
    }

    // Delete the old Settings Table
    $database->query("DROP TABLE IF EXISTS `" . TABLE_PREFIX . "mod_foldergallery_settings`;");

    // Create the new Settings Table
    $sql = "CREATE TABLE IF NOT EXISTS `" . TABLE_PREFIX . "mod_foldergallery_settings` ("
            . "`id` int(11) NOT NULL AUTO_INCREMENT,"
            . "`section_id` int(11) NOT NULL,"
            . "`s_name` varchar(100) NOT NULL,"
            . "`s_value` TEXT NOT NULL,"
            . "PRIMARY KEY (`id`));";
    $database->query($sql);

    // Write the new Settings
    foreach ($settings as $value) {
        $section_id = $value['section_id'];
        foreach ($value as $key => $val) {
            // Prevent entries with numeric values (they are generated by fetchRow)
            if (is_numeric($key)) {
                continue;
            }
            // The following values are no longer needed
            if ($key == 'section_id') {
                continue;
            }
            if ($key == 'thumb_size') {
                continue;
            }
            if ($key == 'ratio') {
                continue;
            }

            $sql = "INSERT INTO `" . TABLE_PREFIX . "mod_foldergallery_settings` (`id`, `section_id`, `s_name`, `s_value`) VALUES "
                    . "(null, '" . $section_id . "', '" . $key . "', '" . $val . "');";
            $database->query($sql);
        }
        /**
         * The thumbnail Settings are now stored as a serialized array
         * the folowing switch statement calculates the new values
         */
        switch ($value['ratio']) {
            case 1:
                $thumbSettings = array(
                    'image_resize'  => true,
                    'image_x'       => $value['thumb_size'],
                    'image_y'       => $value['thumb_size']
                );
                break;
            case 1.3333:
                $thumbSettings = array(
                    'image_resize'  => true,
                    'image_x'       => $value['thumb_size'],
                    'image_y'       => floor($value['thumb_size']*3/4)
                );
                break;
            case 0.75:
                $thumbSettings = array(
                    'image_resize'  => true,
                    'image_x'       => floor($value['thumb_size']*3/4),
                    'image_y'       => $value['thumb_size']
                );
                break;
            case 1.7778:
                $thumbSettings = array(
                    'image_resize'  => true,
                    'image_x'       => $value['thumb_size'],
                    'image_y'       => floor($value['thumb_size']*9/16)
                );
                break;
            case 0.5625:
                $thumbSettings = array(
                    'image_resize'  => true,
                    'image_x'       => floor($value['thumb_size']*9/16),
                    'image_y'       => $value['thumb_size']
                );
            default:
                break;
        }
        /**
         * the folowing values are default for new pages. As there was no
         * equivalten value before, we set them on update to default.
         */
        $thumbSettings['image_ratio_fill'] = false;
        $thumbSettings['image_ratio_crop'] = true;
        $thumbSettings['image_background_color'] = '#FFFFFF';
        

        $sql = "INSERT INTO `" . TABLE_PREFIX . "mod_foldergallery_settings` (`id`, `section_id`, `s_name`, `s_value`) VALUES "
             . "(null, '" . $section_id . "', 'tbSettings', '".serialize($thumbSettings)."');";
        $database->query($sql);
    }
}
/**
 * END: Create new settings table
 */


/**
 * alter categories Table to allow more than 255 characters as categoriedescription
 */
$sql = "ALTER TABLE `".TABLE_PREFIX."mod_foldergallery_categories` CHANGE `description` `description` TEXT NOT NULL DEFAULT '';";
$database->query($sql);
/**
 * END alter categories Table
 */

/**
 * There are files which are moved or no longer needed.
 * So we need to delete the old files and directories
 */
$fg_path =  WB_PATH.'/modules/foldergallery/';
$file_list = array(
    $fg_path.'modify_cat.php',      // Moved to admin
    $fg_path.'modify_cat_sort.php', // Moved to admin
    $fg_path.'modify_settings.php', // Moved to admin
    $fg_path.'modify_thumb.php',    // Moved to admin
    $fg_path.'save_cat.php',        // Moved to admin
    $fg_path.'save_files.php',      // Moved to admin
    $fg_path.'save_settings.php',   // Moved to admin
    $fg_path.'sync.php',            // Moved to admin
    $fg_path.'frontend.css.orig',   // No longer needed
    $fg_path.'scripts/backend.functions.php', // Moved to admin/scripts
    $fg_path.'scripts/delete_cat.php',      // Moved to admin/scripts
    $fg_path.'scripts/delete_img.php',      // Moved to admin/scripts
    $fg_path.'scripts/move_down.php',       // Moved to admin/scripts
    $fg_path.'scripts/move_up.php',         // Moved to admin/scripts
    $fg_path.'scripts/quick_img_sort.php',  // Moved to admin/scripts
    $fg_path.'scripts/reorderCNC.php',      // Moved to admin/scripts
    $fg_path.'scripts/reorderDND.php',      // Moved to admin/scripts
    $fg_path.'templates/modify_cat.htt',    // Moved to admin/templates
    $fg_path.'templates/modify_cat_sort.htt', // Moved to admin/templates
    $fg_path.'templates/modify_settings.htt', // Moved to admin/templates
    $fg_path.'templates/modify.htt',        // Moved to admin/templates
    $fg_path.'images/eck.gif',              // No longer needed
    $fg_path.'images/crumbs.png'            // No longer needed
);

foreach($file_list as $file) {
    if(file_exists($file)) {
        unlink($file);
    }
}
/**
 * END: Deleting old files
 */


/**
 * END: Update from Version 1.20/1.21
 */

?>
